version: '3'

services:
  app:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: bash -c "apt-get update && apt-get install -y libzip-dev && docker-php-ext-install zip pdo pdo_mysql && pecl install redis && docker-php-ext-enable redis && php-fpm"
    depends_on:
      - redis

  composer:
    image: composer:latest
    volumes:
      - .:/app
    command: install

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  vendor:
